### ISSUE TITLE
La Franciosetta--words missed!

### ISSUE THREAD

**Issue by Puzzle88Piecer** [nkronenfeld/RenDance#21]
Sue has found 2 places in this very long dance where words seem to have been missed from both transcription and translation.  One problem (around line 146) seems not to greatly affect the meaning.  In the other instance (around line 186), we seem to have missed a set of riverenzette (one forward, one backwards).  To clarify, the dance had already had riv forward, riv back, double turning to the L; now we add riv forward, riv back, double turning to the R.  Reconstruction will definitely need to be checked.

**Comment by nkronenfeld** [comment]
I checked, it's there.
