### ISSUE TITLE
Proofread all italian

### ISSUE THREAD

**Issue by nkronenfeld** [nkronenfeld/RenDance#5]
Go over all the Italian text, comparing it to our new photos of the original manuscript, and check for errors and clarity.

**Comment by Puzzle88Piecer** [comment]
This is basically done now.  Sue has **not** finished checking (or translating for the first time?) the introduction; we only have about half the text.

**Comment by Puzzle88Piecer** [comment]
Closing this issue today; introduction has still not been fully checked/completed, but a separate issue has been opened for that.
