### ISSUE TITLE
passo intraverso or passo in traverso

### ISSUE THREAD

**Issue by nkronenfeld** [nkronenfeld/RenDance#7]
pick one in our translation, standardise on it.

**Comment by Puzzle88Piecer** [comment]
According to Sue: Though either solution, applied consistently, would be possible, "in traverso" would be much the more standard way to do this in modern Italian.  We are trying to make this easier for modern scholars to read/work with.  Therefore, "in traverso should really win.  Now we just have to implement.  :-)

**Comment by Puzzle88Piecer** [comment]
These have all been normalized to "passo in traverso".  Closing.
