### ISSUE TITLE
I Tromboni, 5:10:23

### ISSUE THREAD

**Issue by nkronenfeld** [nkronenfeld/RenDance#8]
New paragraph begins with Dia?
If so, this clearly shouldn't be the first word in the English.  How do we want to handle the bolding that shows the start of paragraphs?

**Comment by Puzzle88Piecer** [comment]
Can't we just resolve this by putting in our introduction and/or notes that the words in bold are the ones that actually start the paragraphs in the Italian?  That would be my (Sue's) preference.

**Comment by nkronenfeld** [comment]
Not really, it's just a question of whether the first word in the english paragraph should be bold, or the word that coresponds to the first word in the italian paragraph.

**Comment by nkronenfeld** [comment]
Sue says the corresponding word, that's fine with me.
